### ISSUE TITLE
Fetured Video, does not display anything.

### ISSUE THREAD

**Issue by UnderscoreAngel** [thistlecafe/cosmic-cat#125]
### Type

Page Renderer

### Page URL

youtube.com/channel/channelid/featured

### Branch

main

### Version

0.6.29

### A brief description

instead of loading a channel trailer, or the featured content, it just doesn't display anything.

### Screenshots or videos

![imagen](https://user-images.githubusercontent.com/105066360/227332407-f0609920-4c1d-4144-a2e9-23b48393f6a4.png)

### Console output

DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/7a427f25/jsbin/webcomponents-sd.vflset/blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/7a427f25/jsbin/custom-elements-es5-adapter.vflset/blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/7a427f25/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Cosmic Cat.user.js:5512 Storage.init storage has init.
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/7a427f25/jsbin/custom-elements-es5-adapter.vflset/blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/7a427f25/jsbin/webcomponents-sd.vflset/blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Cosmic Cat.user.js:5970 [Searchbox] Couldn't init!
 TypeError: Cannot read properties of undefined (reading 'masthead')
    at Cosmic Cat.user.js:5958:24
    at Cosmic Cat.user.js:5972:11 
Trying again in 1 second.
(anonymous) @ Cosmic Cat.user.js:5970
(anonymous) @ Cosmic Cat.user.js:5972
setTimeout (async)
(anonymous) @ Cosmic Cat.user.js:5914
Promise.then (async)
(anonymous) @ Cosmic Cat.user.js:5847
(anonymous) @ Cosmic Cat.user.js:6341
(anonymous) @ Cosmic Cat.user.js:6342
VMp1qry3zc6hg @ Cosmic Cat.user.js:6342
Ut @ injected-web.js:1
(anonymous) @ Cosmic Cat.user.js:1
Et @ injected.js:1
Dt @ injected.js:1
St @ injected.js:1
(anonymous) @ injected.js:1
We @ injected.js:1
$t @ injected.js:1
(anonymous) @ injected.js:1
await in (anonymous) (async)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/7a427f25/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Cosmic Cat.user.js:6229 {owner: {…}, time: 'LIVE', views: '153 visualizaciones', title: 'welcome', id: 'TZdrchBZRTw', …}
Cosmic Cat.user.js:6330 Loaded page in:  -1482 ms
featured:1 The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by UnderscoreAngel** [comment]
i have no idea if the console output is right
